### ISSUE TITLE
Not working wtih Unity 2019.3.f6

### ISSUE THREAD

**Issue by tusharsankhala** [DenizBicer/Pixel-Sorting#1]
Hi,

I am getting just a white raw image quad, upon running the scene.
I checked the render texture image which sorts the pixel and there is no information in the image being written.

What could be the issue.
Thanks in advance.

**Comment by DenizBicer** [comment]
Hi tusharsankhala,

Do you get any error messages? maybe related to the **thread group count**?

**Comment by tusharsankhala** [comment]
Hi,

Thanks for the reply,
I didn't got any error, console is clear, tried even with reducing the thread count to 8 in the shader as well and the script but same result.

By any chance have you tired with Unity 2019.3.0f6.

Thanks

**Comment by DenizBicer** [comment]
I just tried it on 2019.3.0f6, but couldn't reproduce your issue.

**Comment by geslotencirkel** [comment]
how does it work? Tried it with 2020.2.a7, 2019.3.7f and 2019.2.3f1. Mouse clicking on the canvas is supposed to cause the pixel sort effect? Building a player also seems to not function here.

**Comment by DenizBicer** [comment]
there's no interaction, when you play it, it starts immediately. 
Do you get any error messages? 
Which operating system and graphics api are you running on?
Have you tried changing the thread group count?

**Comment by geslotencirkel** [comment]
windows 8.1, D3D 11.
No console errors, but on opening the project I am also seeing a blank white screen - cause by the Raw Image scripts on Background and Rawimage. 

![image](https://user-images.githubusercontent.com/12006521/80278255-107da280-86f5-11ea-8325-f36145d4634b.png)
![image](https://user-images.githubusercontent.com/12006521/80278261-1a9fa100-86f5-11ea-8535-94674208c27b.png)

i assume this is normal.
These are the properties for the PixelSort layer
![image](https://user-images.githubusercontent.com/12006521/80278280-37d46f80-86f5-11ea-8e57-a66c5c18a8eb.png)

No console errors.

I changed thread count in 
https://github.com/DenizBicer/Pixel-Sorting/blob/master/Assets/PixelSorter.compute#L48
https://github.com/DenizBicer/Pixel-Sorting/blob/master/Assets/PixelSorter.compute#L63

to 4,1,1,
and
https://github.com/DenizBicer/Pixel-Sorting/blob/master/Assets/PixelSort.cs#L110

to 4

Not getting any results yet.

**Comment by DenizBicer** [comment]
could you check if your system supports compute shaders? https://docs.unity3d.com/ScriptReference/SystemInfo-supportsComputeShaders.html

**Comment by geslotencirkel** [comment]
oh yes. nvidia 1080 here. 
I can only cause a compute shader error if I emulate a Shader Model 3 system in Unity editor.
Otherwise the console is blank.
